### ISSUE TITLE
rendering code in .md files

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#21]
Hi @mjones01 a few notes about rendering in .md

To create a code block, please use 4 spaces per line. 

so 

```
# hi i'm code
code <- code+1
```

indented 4 spaces. you don't have to specify bash or use ```bash. highlight js will figure out how to render it. (that is what we're using currently for our code blocks). 

If you see any issues please let me know. i'm fixing a few blocks in Git03 but i'll let you clean up the rest when you edit the materials as we discussed today.

**Comment by mjones01** [comment]
Ok.  Sounds good. I'll leave this Issue open until we've cleaned this up in all the .mds.

**Comment by lwasser** [comment]
perfect. Thank you!

**Comment by mjones01** [comment]
Done.  Closing Issue.
