### ISSUE TITLE
Home page: Friday is currently listed as Thursday

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#22]
http://neon-workwithdata.github.io/neon-data-institute-2016/

On the home page agenda, Friday is currently listed as Thursday 23 June.  

@lwasser I know you were working on the Friday/Capstone materials yesterday and don't want to make changes in case you edits aren't merged yet.

**Comment by lwasser** [comment]
Oh - I have a bunch of updates to push up - that being one of them!
Good catch though. At first I was confused by this as it looks fine on my screen but of course I'm working locally. I'll push this up now.

**Comment by lwasser** [comment]
addressed! 49a3bbe
