### ISSUE TITLE
Agenda for the week long institute.

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#23]
We currently don't have an overall agenda for the institute. Should we make one that just shows what we will be doing each "session" and who is speaking generally?

@mjones01 thoughts?

**Comment by mjones01** [comment]
I've been debating this, but I think yes. We definitely need one internally for us & the other instructors (currently the Working Agenda doc - and it can be cleaned up as we get closer).  If we post one, it would be a single place for everyone to go and would presumably be comforting for the participants.  

We need to decide how/if we want to update it as the week goes if we adjust the schedule.  A posted but not updated agenda could cause more confusion than it is worth.  

If we add it, I don't think the link should go live until we have it set.

**Comment by lwasser** [comment]
ok sounds good. The main "sessions" are fixed at this point. We could add that now.
The timing of individual activities may shift just a bit.

**Comment by mjones01** [comment]
One possibility would be to simple add to each day's home page simple text with times. This would add 2 (or Monday 3) lines of text but give them the times they are expected to be here.  

Page preview: 

 # About
 # Learning Objectives 
 # Download Data 

Morning Session: 8-12
Afternoon Session: 1-6
Evening Session: 8-10

 # Links for Tutorials

**Comment by mjones01** [comment]
Agenda has been added to the home page.  Close the Issue?

**Comment by lwasser** [comment]
Yes - close it! Thank you.
