### ISSUE TITLE
youtube link on front page broken

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#3]
I tried to fix but unsure what link this should be.

**Comment by lwasser** [comment]
what does "front page" mean?

http://neon-workwithdata.github.io/neon-data-institute-2016/ 
there is no video on this page. please provide a link so i can better understand what this issue means.

**Comment by mjones01** [comment]
On the home page, the little YouTube icon on the left sidebar.  When I click on it, it takes me to this page: https://www.youtube.com/create_channel?upsell=channel (to create my own channel), not the NEON channel.  This is broken on NDS too.

**Comment by lwasser** [comment]
fixed! 
1e2a75079808d1a66b4c7e28e2a6fef191b5a2a5

the author_bio include had a code error!
