### ISSUE TITLE
Git lessons - Please call the NEON repo "MAIN" rather than master, Please use "repo" consistently

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#37]
@mjones01 when you get back in tomorrow (Wednesday June 1) please do the following:

Currently the content in the git lessons isn't consistent. Please review and make sure
1. we use "Repo" consistently". i added a paragraph about "repo" vs repository on git 1. so let's use "repo" after that. repo and repository are used throughout in an inconsistent way. 
2. Please make sure the NEON repo is always called NEON MAIN rather than "master". Master can get confusing because you can have a master branch. Thus, please use main. I've tried to fix this throughout as well. 
3. Please spell check lessons - i've tried to catch issues but may have missed some. I've also fixed many typos and broken links. Please build locally and make sure things are working. 
   Thank you.

**Comment by lwasser** [comment]
update - i found this and think "central repo" may be a better term

https://ru.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow

let's use that instead. i think i switched things to MAIN but let's use CENTRAL REPO for the NEON repo.

**Comment by mjones01** [comment]
Progress on Git 01- 05, Git 07: 
- repo used throughout (not in Git 01, concept introduced in Git 02, and not in the image captions). 
- text switched to "central" repo, not "main" or "master".  
- spell check complete
  Will add all of these to Git 06 on edits first thing in the AM.

**Comment by mjones01** [comment]
Completed throughout series.  Find (and manual replace) for all "main" and "master".  PR #48 & PR #46. Closing Issue.
