### ISSUE TITLE
Please add a screenshot to git05.

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#38]
Hi @mjones01 will you please add a screen shot or two in this lesson:
It should show what it would look like with a .md file , in the correct directory in the repo. 

You have a file already in there with your name on it so maybe just make a fork of the repo and take a screen grab from your fork. 
http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute2/git05

let me know if this is unclear.

**Comment by mjones01** [comment]
Done.
