### ISSUE TITLE
Please review git06

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#39]
http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute2/git06

hey @mjones01 please review git06. I think some screen shots would be very helpful if we aren't going to do a screencast - OR see if there is  a screen cast on youtube. Also - the end of the lesson was somewhat rough - i did a bit of editing however please read it through carefully and make sure it will make sense to participants. I think some screenshots will go a long way.

**Comment by lwasser** [comment]
Also - i think we should have explicit steps to submitting the PR -- this could be in a challenge box in Git06 - at the very bottom. Have them:
1. Take their edited markdown file - make sure all of the components are there
2. push to their github.com fork and 
3. submit a PR.

This could go on the activity page but i think it would be better in Git06 as the activity page is designed more for people who've used git before.

**Comment by mjones01** [comment]
@lwasser  RE the second comment here -- based on the lesson it appears you added this.  I've edited what is there and changed the title from "Challenge" to "Activity: Submit Pull Request for Week 2 Assignment" to be consistent with other Pre-Institute series.

I've added screenshots throughout and edited the full lesson for content, readability, and style.  
Closing this issue.
