### ISSUE TITLE
New Universal Knitr Code!

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#41]
Hey @mjones01 I have created some new knitr code that is much better than the old code.

Essentially it takes the directory that you give it and knits everything in there. Then puts the code, and associated outputs in the correct DIR. That way we don't need a knitr script in each directory.  I will be deleting the knitr scripts from all directories over the next few days. I'll wait to do the rmd one until i use it on that dir given it's pre-institute rather than institute. 

https://github.com/NEON-WorkWithData/neon-data-institute-2016/blob/gh-pages/code/knit-RMD-2-MD.R

**Comment by mjones01** [comment]
This code is working great.  Any reason to not close this issue?

**Comment by lwasser** [comment]
Awesome. Glad it's working! Yes close it please.
