### ISSUE TITLE
CSS notice boxes; gap above header2

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#44]
http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute2/git01

First blue notice box:  the gap above the h2 Additional Resources needs to be smaller. 
Note: this is formatted with div tags not the {: .notice} tag -- not sure if that matters.

**Comment by lwasser** [comment]
i'm pretty sure this was fixed. have a look tomorrow and see if it looks better. i did many css edits at once so it's not explicit in the commits.

**Comment by mjones01** [comment]
Yep.  Looks good.
