### ISSUE TITLE
Blue Links in Blue Notice boxes hard to read

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#45]
http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute2/git02

Lower priority but I find the links, how styled in blue, hard to read in the blue notice boxes.  We may want to adjust the coloring of one or the other.  I'd opt for paler boxes.

**Comment by lwasser** [comment]
fixed - 
ca28a194a324998f81b2f8fe1bcd508db9d700d8
