### ISSUE TITLE
Use of btn-success & btn-inverse

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#50]
We currently have two different button styles used in the Institute materials.  From the text, I don't understand the different use cases: 

btn-success - blue with white text (as on http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute1/rep-sci) 

btn-inverse - black with blue text (as on http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/pre-institute2/git04)  

If there is no difference, I think we should choose one and present a consistent appearance. I'd vote for "btn-success" as we also use that for downloading data and other clickable buttons throughout the sites.

**Comment by lwasser** [comment]
gosh i though i fixed that blue link text issue. 

I'd like to always use the blue button for data downloads like on the NEON site.
Then use a second style for all other buttons.

So let's change all NON data download buttons to .btn-info
i'll style the colors to make it look better - i'm thinking grey might be nice and simple.

**Comment by lwasser** [comment]
i've modified it to be a white button with a blue border. it's simpler. use btn btn-info .

**Comment by mjones01** [comment]
to clarify: 
btn-success  - data download only

btn-info - all other buttons

btn-inverse - nothing

How much retro active changing do we want to do?  (e.g. Set up  to Week 2 materials?)

**Comment by neondataskills** [comment]
Correct.

Btn-success for data downloads only
Btn-info for all other buttons on the page.

I fixed the styles last night BUT let me know if you catch anything odd.

let's just go through all of the lessons. I'm working in the git lessons and I think I've made the changes there. I'll do a review. If you can review setup and wk 1, we will be set. Thank you.

**Comment by mjones01** [comment]
Done. 
None to fix in week 0, both lessons fixed in week 1.  Closing Issue.
