### ISSUE TITLE
Wednesday - no banner image

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#52]
@lwasser On the Wednesday home page there is no banner but text saying "Comparing Ground to Airborne - uncertainty feature image".  

http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/institute-day3/

All other daily home pages use the main DI16 banner.  Should I add it here as well, or does Colin have a new banner that needs to be added here?

**Comment by neondataskills** [comment]
Hi Megan,
Go ahead and add the banner - just like it's on the other landing pages. Thank you for catching that!
Leah

**Comment by mjones01** [comment]
Done. Added About text as well (copied from the home page).  Closing Issue.
