### ISSUE TITLE
Monday Agenda link seems wrong

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#54]
http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/institute-day1/

The Agenda button goes directly to an NDS HDFView tutorial.  This doesn't seem correct, where should it link to?  

However -- do we even need an agenda button here (seems bit weird as the whole page is titled Agenda: Monday ...)? The schedule is directly below and visible on the same screen (unless maybe viewing on a mobile device).  No other daily home pages have an Agenda button.

**Comment by lwasser** [comment]
That was just a test. I was thinking about providing a week long agenda to participants but I'm still on the fence about where to put that. I'm now thinking it should go on the side bar as a link on every page potentially. I think we can remove that link for the time being.

**Comment by lwasser** [comment]
removed.
