### ISSUE TITLE
Daily Home Pages

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#55]
@lwasser  Do we want to add learning objectives and data downloads (as grey box material) on each day's homepage?  Tuesday has text stating this but it isn't yet done (http://neon-workwithdata.github.io/neon-data-institute-2016/tutorial-series/institute-day2/), none of the other day's have this.  

I think the daily learning objectives would be a good addition as it looks like more individual pages don't (yet) have learning objectives.  If we do want add them, I can transfer them directly from the working agenda document. 

The addition of data downloads should depend on how many data sets will be used in given day -- if one or few throughout the day then it makes a lot of sense; if different for each section, the maybe not.

**Comment by lwasser** [comment]
As long as the grey box stays small (the agenda needs to not be pushed down too far), I think that is a great idea. Monday afternoon and evening / Tuesday morning / afternoon will have different sets of learning objectives.

Thank you, Megan

**Comment by lwasser** [comment]
Ok i've thought about this more. I'd like to keep this very simple for now. i've added a template on each page. all that each page will need is a data link and objectives. monday and tuesday will have a few extra but i'd like to keep objectives very high level for each day!

**Comment by mjones01** [comment]
Done. Commit bcb25c0.  Separate issue (#58) for Wednesday and Thursday data download links. Closing this issue.
