### ISSUE TITLE
code for r package install

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#60]
The code below can be used to run AOP specific functions. Please test it out and let me know if you run into issues!
@mjones01 

``` r
# install devtools (only once)
install.packages("devtools")
# call devtools library
library(devtools)

## install from github
install_github("lwasser/neon-aop-package/neonAOP")
## call library
library(neonAOP)
```

**Comment by mjones01** [comment]
Seems to work beautifully!  I just completed plot-SHIspectra-signature-R.Rmd using this instead of source and the full lesson worked.

**Comment by lwasser** [comment]
it does!!?? that's awesome. thank you for testing it. so we can update the lessons to use the package rather than the source file. i think that's better because i can always update it for everyone at the same time if we run into bugs.

**Comment by mjones01** [comment]
Currently I'm adding this code into the lessons: 

`## import functions`
`# install devtools (only if you have not previously intalled it)`
`#install.packages("devtools")`
`# call devtools library`
`#library(devtools)`

`# install from github`
`#install_github("lwasser/neon-aop-package/neonAOP")`
`# call library`
`library(neonAOP)`

`#source("/Users/lwasser/Documents/GitHub/neon-aop-package/neonAOP/R/aop-data.R")`

Should I just delete the commented out source part?  Should anything else be changed?

**Comment by mjones01** [comment]
And I should mention, on both PC and Mac.

**Comment by lwasser** [comment]
Thank you Megan. Please leave the source commented out. I think it's good for people to see t hat they can source functions
If they don't want to create a package. This is nice for working locally and reusing functions. it's just better for us to not have to maintain 25 copies of a R script :)

Please do test each lesson just to make sure it all works in each lesson.
IMPORTANT: for each lesson - CLEAR ALL ENVIRONMENT VARIABLES FIRST. Then test. I've run into mistakes I made because of a variable still hanging around that was useful. :)

Leah

**Comment by mjones01** [comment]
No worries.  All reviewed lessons (PC and Mac) have been reviewed with "fresh" environments.

**Comment by lwasser** [comment]
great. Can we close this issue now? I'm really excited that the package is working. it wasn't too hard to build. if you want to see how it works sometime i can show you.

**Comment by mjones01** [comment]
Sounds good. Closing.
